### ISSUE TITLE
Ajudinha.

### ISSUE THREAD

**Issue by f1gur4nt** [dheisom-gomes/TicTacToe#1]
Dheisom, sabe aquele repositório seu que usa javascript e socket? Que se conectava a um servidor escrito em python. 

Onde ele está? Não acho em lugar algo. Preciso dele pra uma ferramenta que estou pretendo escrever.

**Comment by dheisom-gomes** [comment]
Eu apaguei ele faz um tempo, mas basicamente eu inseria o script na página depois de ligar um servidor websocket no backend, com isso o front conectava direto
